#!/bin/bash
#
# Copyright (c) Sylvestre Ledru <sylvestre@debian.org>, 2013-2014 under the
# terms and conditions of the Debile project, MIT/Expat. You should have
# recieved a copy of the license with this script.
#
# Hack the system to make sure clang is used by default instead of gcc.
# Same hack is used for http://clang.debian.net/

set -x
echo "Entering customization script..."

echo "Install of clang-3.4"
apt-get update
apt-get install --yes --no-install-recommends --force-yes clang-3.4

echo "Replace gcc, g++ & cpp by clang"
VERSIONS="4.6 4.7 4.8 4.9"
cd /usr/bin
for VERSION in $VERSIONS; do
    rm -f g++-$VERSION gcc-$VERSION cpp-$VERSION
    ln -s clang++ g++-$VERSION
    ln -s clang gcc-$VERSION
    ln -s clang cpp-$VERSION
    echo "gcc-$VERSION hold"|dpkg --set-selections
    echo "g++-$VERSION hold"|dpkg --set-selections
done
cd -

echo "Check if gcc, g++ & cpp are actually clang"
gcc --version|grep clang > /dev/null || exit 1
cpp --version|grep clang > /dev/null || exit 1
g++ --version|grep clang > /dev/null || exit 1
