#!/usr/bin/env python
#
# Copyright (c) Paul R. Tagliamonte <paultag@debian.org>, 2014 under the
# terms and conditions of the Debile project, MIT/Expat. You should have
# recieved a copy of the license with this script.
#
# If we're running as !(root), exit 1.
#
# Ohkay, a few jobs. We need to digest the .tar.gz and write the values
# we care about to /etc/debile/slave.yaml
#
# After that's all sorted, we'll su over to Debian-debile-unpriv and import
# our OpenPGP keys

import os
import sys
import yaml
import tarfile
from contextlib import contextmanager

from debile.utils.commands import run_command

DEBILE_USER = "Debian-debile-unpriv"
DEFAULT_DEBILE_CONF = "/etc/debile/"

@contextmanager
def editconf(where=None):
    if where is None:
        where = DEFAULT_DEBILE_CONF + "slave.yaml"
        with open(where, 'r') as fd:
            info = yaml.load(fd)
            yield info
        # We've got control again. Let's save this.
        with open(where, 'w') as fd:
            yaml.dump(info, fd)


# if os.geteuid() != 0:
#     print("Error: I'm not root.")
#     print("   I require `su` and write to /etc")
#     print("   please re-run with sudo or whatever.")
#     exit(1)


def cg(tarfile):
    def get(what):
        return tarfile.extractfile(what).read().strip()
    return get


with tarfile.open(sys.argv[1], "r:gz") as tf:
    get = cg(tf)
    name = get("name")
    key = get("fingerprint")
    kname = "%" + (name)

    with editconf() as config:
        config['gpg'] = key
        r = config['xmlrpc']
        r['keyfile'] = DEFAULT_DEBILE_CONF + name + ".key"
        r['certfile'] = DEFAULT_DEBILE_CONF + name + ".crt"
