# Create a local-use Debile slave.
#
# VERSION   0.1
FROM        paultag/debile-slave
MAINTAINER  Paul R. Tagliamonte <paultag@debian.org>

ADD ursae.json /usr/share/dput-ng/profiles/
ADD slave.yaml /etc/debile/
